baseURL: https://ranger6.github.io/acme/
#baseURL: http://muir.remulac.fr/
#baseURL: ""
#relativeURLs: true
publishDir: "docs"
languageCode: en-us
title: Acme Site
#theme: github.com/hugoinaction/Eclectic
theme: ananke
